services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - NUXT_PUBLIC_API_BASE_URL=${BACKEND_API_URL}
      - NUXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
      - NUXT_PUBLIC_BACKEND_HOST=backend
      - NUXT_PUBLIC_BACKEND_PORT=443
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - urban_renewal_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:80"
    environment:
      - CI_ENVIRONMENT=development
      - APP_BASE_URL=${BACKEND_URL}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - urban_renewal_network

  mariadb:
    image: mariadb:11.4
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      timeout: 10s
      retries: 5
      interval: 10s
      start_period: 60s
    restart: unless-stopped
    networks:
      - urban_renewal_network

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - urban_renewal_network

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - urban_renewal_network

volumes:
  mariadb_data:

networks:
  urban_renewal_network:
    driver: bridge