services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped
    networks:
      - urban_renewal_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:80"
    environment:
      - CI_ENVIRONMENT=development
      - APP_BASE_URL=http://localhost:${BACKEND_PORT}
    restart: unless-stopped
    networks:
      - urban_renewal_network

networks:
  urban_renewal_network:
    driver: bridge