// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/9/14 下午6:11:09
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../nuxtui-tailwind.config.mjs";
const config = [
{"content":{"files":["D:/Bonus/0814_web_45000/urban_renewal/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Bonus/0814_web_45000/urban_renewal/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Bonus/0814_web_45000/urban_renewal/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Bonus/0814_web_45000/urban_renewal/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Bonus/0814_web_45000/urban_renewal/frontend/plugins/**/*.{js,ts,mjs}","D:/Bonus/0814_web_45000/urban_renewal/frontend/composables/**/*.{js,ts,mjs}","D:/Bonus/0814_web_45000/urban_renewal/frontend/utils/**/*.{js,ts,mjs}","D:/Bonus/0814_web_45000/urban_renewal/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Bonus/0814_web_45000/urban_renewal/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Bonus/0814_web_45000/urban_renewal/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Bonus/0814_web_45000/urban_renewal/frontend/app.config.{js,ts,mjs}"]}},
{"darkMode":"class"},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;