#!/bin/bash

# Urban Renewal Voting System - 統一環境管理腳本
# 都更計票系統 - 環境管理
#
# 使用方式：
#   ./scripts/deploy.sh production  # 啟動正式環境
#   ./scripts/deploy.sh dev        # 啟動開發環境
#   ./scripts/deploy.sh            # 預設開發環境

set -e

# 顏色定義
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 接收環境參數，預設為 dev
ENV=${1:-dev}

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  都更計票系統 - 環境啟動${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# 檢查環境參數
if [[ "$ENV" != "production" && "$ENV" != "dev" ]]; then
    echo -e "${RED}❌ 錯誤：不支援的環境 '$ENV'${NC}"
    echo -e "${YELLOW}支援的環境：production, dev${NC}"
    exit 1
fi

echo -e "${GREEN}📦 目標環境：${ENV}${NC}"
echo ""

# 檢查環境配置檔案
ENV_FILE="docker/.env.$ENV"
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${RED}❌ 環境配置檔案不存在: $ENV_FILE${NC}"
    exit 1
fi

echo -e "${GREEN}✓ 找到環境配置檔案: $ENV_FILE${NC}"

# 複製環境配置到 docker/.env
echo -e "${BLUE}📋 複製環境配置...${NC}"
cp "$ENV_FILE" docker/.env
echo -e "${GREEN}✓ 已複製到 docker/.env${NC}"

# 生成 backend/.env
echo -e "${BLUE}🔧 生成後端配置 backend/.env...${NC}"

# 從 docker/.env 讀取變數
source docker/.env

# 生成 CodeIgniter 4 格式的 .env
cat > backend/.env << EOF
# Auto-generated from docker/.env.$ENV
# Generated at: $(date '+%Y-%m-%d %H:%M:%S')
# DO NOT EDIT MANUALLY - This file is auto-generated by scripts/deploy.sh

CI_ENVIRONMENT = $CI_ENVIRONMENT

#--------------------------------------------------------------------
# DATABASE
#--------------------------------------------------------------------
database.default.hostname = $DB_HOST
database.default.database = $DB_DATABASE
database.default.username = $DB_USERNAME
database.default.password = $DB_PASSWORD
database.default.DBDriver = MySQLi
database.default.DBPrefix =
database.default.port = 3306

#--------------------------------------------------------------------
# DEBUG
#--------------------------------------------------------------------
# Debug level: 0=off, 1=error, 2=debug, 3=info, 4=all
CI.debug = $CI_DEBUG
EOF

echo -e "${GREEN}✓ 已生成 backend/.env${NC}"
echo ""

# 顯示配置摘要
echo -e "${BLUE}📊 配置摘要：${NC}"
echo -e "  環境: ${YELLOW}$CI_ENVIRONMENT${NC}"
echo -e "  資料庫主機: ${YELLOW}$DB_HOST${NC}"
echo -e "  資料庫名稱: ${YELLOW}$DB_DATABASE${NC}"
echo -e "  資料庫使用者: ${YELLOW}$DB_USERNAME${NC}"
echo -e "  Debug 等級: ${YELLOW}$CI_DEBUG${NC}"
echo ""

# 檢查 docker-compose 檔案
COMPOSE_FILE="docker/docker-compose.$ENV.yml"
if [ ! -f "$COMPOSE_FILE" ]; then
    echo -e "${RED}❌ Docker Compose 檔案不存在: $COMPOSE_FILE${NC}"
    exit 1
fi

echo -e "${GREEN}✓ 找到 Docker Compose 檔案: $COMPOSE_FILE${NC}"
echo ""

# 檢查並清理舊容器
echo -e "${BLUE}🔍 檢查舊容器...${NC}"

# 根據環境設定容器名稱模式
if [ "$ENV" = "production" ]; then
    CONTAINER_PATTERN="urban_renewal_.*_prod"
else
    CONTAINER_PATTERN="urban_renewal_.*_dev"
fi

# 檢查是否存在相關容器（包含已停止的）
EXISTING_CONTAINERS=$(docker ps -aq --filter "name=${CONTAINER_PATTERN}" 2>/dev/null)

if [ -n "$EXISTING_CONTAINERS" ]; then
    echo -e "${YELLOW}⚠️  發現舊容器，正在清理...${NC}"
    
    # 顯示要清理的容器
    echo -e "${YELLOW}   容器列表:${NC}"
    docker ps -a --filter "name=${CONTAINER_PATTERN}" --format "   - {{.Names}} ({{.Status}})" 2>/dev/null || true
    
    # 停止並移除所有相關容器
    echo -e "${YELLOW}   正在停止並移除...${NC}"
    docker rm -f $EXISTING_CONTAINERS 2>/dev/null || true
    
    # 再次檢查是否清理乾淨
    REMAINING=$(docker ps -aq --filter "name=${CONTAINER_PATTERN}" 2>/dev/null)
    if [ -n "$REMAINING" ]; then
        echo -e "${RED}⚠️  部分容器清理失敗，嘗試強制清理...${NC}"
        docker rm -f $REMAINING 2>/dev/null || true
    fi
    
    echo -e "${GREEN}✓ 舊容器已清理${NC}"
else
    echo -e "${GREEN}✓ 無舊容器${NC}"
fi

# 清理舊的網路（如果存在）
OLD_NETWORK=$(docker network ls --filter "name=docker_urban_renewal_network" -q 2>/dev/null)
if [ -n "$OLD_NETWORK" ]; then
    echo -e "${YELLOW}⚠️  發現舊網路，正在清理...${NC}"
    docker network rm docker_urban_renewal_network 2>/dev/null || true
fi

echo ""

# 檢查前端是否有變更
check_frontend_changes() {
    # 檢查是否存在前端 image
    FRONTEND_IMAGE=$(docker images -q docker-frontend 2>/dev/null)
    
    if [ -z "$FRONTEND_IMAGE" ]; then
        echo -e "${YELLOW}⚠️  前端 image 不存在，需要 build${NC}"
        return 0  # 需要 build
    fi
    
    # 檢查前端檔案是否有變更（與上次 build 比較）
    FRONTEND_HASH_FILE=".frontend_build_hash"
    CURRENT_HASH=$(find frontend -type f \( -name "*.vue" -o -name "*.ts" -o -name "*.js" -o -name "package.json" \) -exec md5sum {} \; 2>/dev/null | sort | md5sum | cut -d' ' -f1)
    
    if [ -f "$FRONTEND_HASH_FILE" ]; then
        LAST_HASH=$(cat "$FRONTEND_HASH_FILE")
        if [ "$CURRENT_HASH" = "$LAST_HASH" ]; then
            echo -e "${GREEN}✓ 前端無變更，跳過 build${NC}"
            return 1  # 不需要 build
        fi
    fi
    
    echo -e "${YELLOW}⚠️  前端有變更，需要 build${NC}"
    echo "$CURRENT_HASH" > "$FRONTEND_HASH_FILE"
    return 0  # 需要 build
}

# 智能檢測前端變更
echo -e "${BLUE}🔍 檢查前端變更...${NC}"
if check_frontend_changes; then
    echo -e "${BLUE}🔨 Build 前端 image...${NC}"
    docker compose -f "$COMPOSE_FILE" build frontend
    echo -e "${GREEN}✓ 前端 build 完成${NC}"
fi
echo ""

# 啟動 Docker Compose
echo -e "${BLUE}🚀 啟動 Docker 服務...${NC}"
echo -e "${YELLOW}執行指令: docker compose -f $COMPOSE_FILE --env-file docker/.env up -d${NC}"
echo ""

docker compose -f "$COMPOSE_FILE" --env-file docker/.env up -d

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  ✓ 啟動完成！${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# 等待後端容器完全啟動
echo -e "${BLUE}⏳ 等待後端容器啟動...${NC}"
sleep 5

# 執行資料庫遷移
echo -e "${BLUE}🔄 執行資料庫遷移...${NC}"
BACKEND_CONTAINER="urban_renewal_backend_${ENV}"

# 檢查容器是否存在且正在運行
if docker ps --format '{{.Names}}' | grep -q "^${BACKEND_CONTAINER}$"; then
    echo -e "${YELLOW}   執行指令: docker exec ${BACKEND_CONTAINER} php spark migrate --all${NC}"
    
    # 執行 migrate
    if docker exec "$BACKEND_CONTAINER" php spark migrate --all 2>&1 | tee /tmp/migrate_output.log; then
        echo -e "${GREEN}✓ 資料庫遷移完成${NC}"
    else
        # 檢查是否是 "沒有新的遷移" 的情況
        if grep -q "Nothing to migrate" /tmp/migrate_output.log 2>/dev/null; then
            echo -e "${GREEN}✓ 資料庫已是最新版本${NC}"
        else
            echo -e "${YELLOW}⚠️  資料庫遷移有警告，請檢查日誌${NC}"
        fi
    fi
    rm -f /tmp/migrate_output.log 2>/dev/null || true
else
    echo -e "${RED}⚠️  找不到後端容器: ${BACKEND_CONTAINER}${NC}"
    echo -e "${YELLOW}   請手動執行: docker exec ${BACKEND_CONTAINER} php spark migrate --all${NC}"
fi
echo ""

# 顯示服務狀態
echo -e "${BLUE}📋 服務狀態：${NC}"
docker compose -f "$COMPOSE_FILE" --env-file docker/.env ps

echo ""
echo -e "${BLUE}💡 常用指令：${NC}"
echo -e "  查看日誌: ${YELLOW}docker compose -f $COMPOSE_FILE logs -f${NC}"
echo -e "  停止服務: ${YELLOW}docker compose -f $COMPOSE_FILE down${NC}"
echo -e "  重啟服務: ${YELLOW}./scripts/deploy.sh $ENV${NC}"
echo -e "  執行遷移: ${YELLOW}docker exec ${BACKEND_CONTAINER} php spark migrate --all${NC}"
echo ""
