#!/bin/bash

# Urban Renewal Voting System - 統一環境管理腳本
# 都更計票系統 - 環境管理
#
# 使用方式：
#   ./scripts/deploy.sh production  # 啟動正式環境
#   ./scripts/deploy.sh dev        # 啟動開發環境
#   ./scripts/deploy.sh            # 預設開發環境

set -e

# 顏色定義
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 接收環境參數，預設為 dev
ENV=${1:-dev}

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  都更計票系統 - 環境啟動${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# 檢查環境參數
if [[ "$ENV" != "production" && "$ENV" != "dev" ]]; then
    echo -e "${RED}❌ 錯誤：不支援的環境 '$ENV'${NC}"
    echo -e "${YELLOW}支援的環境：production, dev${NC}"
    exit 1
fi

echo -e "${GREEN}📦 目標環境：${ENV}${NC}"
echo ""

# 檢查環境配置檔案
ENV_FILE="docker/.env.$ENV"
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${RED}❌ 環境配置檔案不存在: $ENV_FILE${NC}"
    exit 1
fi

echo -e "${GREEN}✓ 找到環境配置檔案: $ENV_FILE${NC}"

# 複製環境配置到 docker/.env
echo -e "${BLUE}📋 複製環境配置...${NC}"
cp "$ENV_FILE" docker/.env
echo -e "${GREEN}✓ 已複製到 docker/.env${NC}"

# 生成 backend/.env
echo -e "${BLUE}🔧 生成後端配置 backend/.env...${NC}"

# 從 docker/.env 讀取變數
source docker/.env

# 生成 CodeIgniter 4 格式的 .env
cat > backend/.env << EOF
# Auto-generated from docker/.env.$ENV
# Generated at: $(date '+%Y-%m-%d %H:%M:%S')
# DO NOT EDIT MANUALLY - This file is auto-generated by scripts/deploy.sh

CI_ENVIRONMENT = $CI_ENVIRONMENT

#--------------------------------------------------------------------
# DATABASE
#--------------------------------------------------------------------
database.default.hostname = $DB_HOST
database.default.database = $DB_DATABASE
database.default.username = $DB_USERNAME
database.default.password = $DB_PASSWORD
database.default.DBDriver = MySQLi
database.default.DBPrefix =
database.default.port = 3306

#--------------------------------------------------------------------
# DEBUG
#--------------------------------------------------------------------
# Debug level: 0=off, 1=error, 2=debug, 3=info, 4=all
CI.debug = $CI_DEBUG
EOF

echo -e "${GREEN}✓ 已生成 backend/.env${NC}"
echo ""

# 顯示配置摘要
echo -e "${BLUE}📊 配置摘要：${NC}"
echo -e "  環境: ${YELLOW}$CI_ENVIRONMENT${NC}"
echo -e "  資料庫主機: ${YELLOW}$DB_HOST${NC}"
echo -e "  資料庫名稱: ${YELLOW}$DB_DATABASE${NC}"
echo -e "  資料庫使用者: ${YELLOW}$DB_USERNAME${NC}"
echo -e "  Debug 等級: ${YELLOW}$CI_DEBUG${NC}"
echo ""

# 檢查 docker-compose 檔案
COMPOSE_FILE="docker/docker-compose.$ENV.yml"
if [ ! -f "$COMPOSE_FILE" ]; then
    echo -e "${RED}❌ Docker Compose 檔案不存在: $COMPOSE_FILE${NC}"
    exit 1
fi

echo -e "${GREEN}✓ 找到 Docker Compose 檔案: $COMPOSE_FILE${NC}"
echo ""

# 檢查並清理舊容器
echo -e "${BLUE}🔍 檢查舊容器...${NC}"
EXISTING_CONTAINERS=$(docker compose -f "$COMPOSE_FILE" ps -aq 2>/dev/null)

if [ -n "$EXISTING_CONTAINERS" ]; then
    echo -e "${YELLOW}⚠️  發現舊容器，正在清理...${NC}"
    
    # 停止並移除舊容器
    docker compose -f "$COMPOSE_FILE" down 2>/dev/null || true
    
    # 額外檢查是否有殘留的容器（使用相同名稱）
    ORPHAN_CONTAINERS=$(docker ps -aq --filter "name=urban_renewal_.*_${ENV}" 2>/dev/null)
    if [ -n "$ORPHAN_CONTAINERS" ]; then
        echo -e "${YELLOW}⚠️  發現殘留容器，正在強制移除...${NC}"
        docker rm -f $ORPHAN_CONTAINERS 2>/dev/null || true
    fi
    
    echo -e "${GREEN}✓ 舊容器已清理${NC}"
else
    echo -e "${GREEN}✓ 無舊容器${NC}"
fi
echo ""

# 啟動 Docker Compose
echo -e "${BLUE}🚀 啟動 Docker 服務...${NC}"
echo -e "${YELLOW}執行指令: docker compose -f $COMPOSE_FILE --env-file docker/.env up -d --build${NC}"
echo ""

docker compose -f "$COMPOSE_FILE" --env-file docker/.env up -d --build

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  ✓ 啟動完成！${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# 顯示服務狀態
echo -e "${BLUE}📋 服務狀態：${NC}"
docker compose -f "$COMPOSE_FILE" --env-file docker/.env ps

echo ""
echo -e "${BLUE}💡 常用指令：${NC}"
echo -e "  查看日誌: ${YELLOW}docker compose -f $COMPOSE_FILE logs -f${NC}"
echo -e "  停止服務: ${YELLOW}docker compose -f $COMPOSE_FILE down${NC}"
echo -e "  重啟服務: ${YELLOW}./scripts/deploy.sh $ENV${NC}"
echo ""
